In [1]:
%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
df=pd.read_html("https://tw.stock.yahoo.com/s/list.php?c=%A8T%A8%AE&rr=0.42911000%201573556409",
               encoding="big5")

In [3]:
len(df)

5

In [4]:
df=df[2]

In [5]:
df

,選擇,股票代號,時間,成交,買進,賣出,漲跌,張數,昨收,開盤,最高,最低
0,NaN,1319 東陽,14:30,46.90,46.85,46.90,▽0.15,825,47.05,47.05,47.40,46.50
1,NaN,1338 廣華-KY,13:30,62.80,62.60,62.90,△0.3,85,62.50,62.50,62.90,62.40
2,NaN,1339 昭輝,14:30,46.15,46.10,46.20,△1.20,462,44.95,45.50,46.40,45.40
3,NaN,1512 瑞利,13:24,5.29,5.20,5.29,△0.09,57,5.20,5.19,5.29,5.19
4,NaN,1521 大億,13:30,64.70,64.70,65.00,▽0.2,46,64.90,64.90,65.00,64.70
5,NaN,1522 堤維西,14:30,29.80,29.80,29.85,△0.45,1504,29.35,29.30,29.90,29.30
6,NaN,1524 耿鼎,13:30,9.97,9.97,10.00,▽0.01,35,9.98,10.00,10.00,9.97
7,NaN,1525 江申,13:21,56.00,55.90,56.00,▽0.2,18,56.20,56.00,56.50,55.60
8,NaN,1533 車王電,13:30,36.80,36.80,36.95,△0.05,54,36.75,36.80,37.20,36.75
9,NaN,1536 和大,13:30,113.00,113.00,113.50,△0.5,401,112.50,113.50,114.00,112.50
10,NaN,1568 倉佑,13:30,19.25,19.20,19.25,▽0.35,236,19.60,19.70,19.70,19.10
11,NaN,1587 吉茂,13:30,16.60,16.50,16.60,0.00,25,16.60,16.55,16.60,16.55
12,NaN,1592 英瑞-KY,13:30,19.80,19.70,19.80,▽0.35,981,20.15,20.15,20.15,19.60
13,NaN,2115 六暉-KY,11:59,39.05,39.00,39.05,△0.10,26,38.95,39.40,39.40,39.05
14,NaN,2201 裕隆,14:30,19.15,19.15,19.20,▽0.05,2640,19.20,19.20,19.30,19.05
15,NaN,2204 中華,13:30,41.00,40.95,41.05,△0.15,250,40.85,41.05,41.05,40.75
16,NaN,2206 三陽工業,13:30,22.15,22.10,22.15,△0.10,764,22.05,22.05,22.15,22.05
17,NaN,2207 和泰車,14:30,575.00,574.00,575.00,△9,326,566.00,567.00,575.00,563.00
18,NaN,2227 裕日車,13:30,265.00,264.50,265.00,△3.5,80,261.50,265.00,265.50,263.00
19,NaN,2228 劍麟,14:30,122.50,122.50,123.00,△1.5,416,121.00,122.50,124.00,121.50
20,NaN,2231 為升,13:30,234.50,234.50,235.50,▽7.0,852,241.50,241.50,243.00,231.50
21,NaN,2233 宇隆,13:30,70.20,70.20,70.40,▽0.1,118,70.30,70.30,70.40,70.10
22,NaN,2236 百達-KY,13:30,21.40,21.10,21.45,▽0.20,15,21.60,21.40,21.40,21.20
23,NaN,2239 英利-KY,13:30,91.10,91.10,91.30,▽1.3,106,92.40,92.10,92.10,91.00
24,NaN,2243 宏旭-KY,13:04,13.40,13.35,13.40,△0.05,8,13.35,13.70,13.70,13.35
25,NaN,2497 怡利電,14:30,23.25,23.25,23.40,▽0.55,462,23.80,23.85,23.85,23.05
26,NaN,3346 麗清,14:30,31.10,31.05,31.10,▽0.05,225,31.15,31.00,31.10,30.85
27,NaN,4551 智伸科,13:30,172.50,172.50,173.50,△1.5,428,171.00,171.50,175.00,171.50
28,NaN,4557 永新-KY,13:15,68.70,68.60,68.80,△0.2,16,68.50,68.50,68.70,68.50
29,NaN,6288 聯嘉,14:30,25.05,25.05,25.10,△0.95,4993,24.10,24.30,25.60,24.25
30,NaN,6605 帝寶,13:30,61.50,61.50,61.70,0.00,92,61.50,61.50,61.70,61.50

In [6]:
df.drop("選擇",axis=1,inplace=True)

In [7]:
df.drop("時間",axis=1,inplace=True)

In [8]:
df.drop("漲跌",axis=1,inplace=True)

In [9]:
df

          股票代號      成交      買進      賣出    張數      昨收      開盤      最高      最低
0      1319 東陽   46.90   46.85   46.90   825   47.05   47.05   47.40   46.50
1   1338 廣華-KY   62.80   62.60   62.90    85   62.50   62.50   62.90   62.40
2      1339 昭輝   46.15   46.10   46.20   462   44.95   45.50   46.40   45.40
3      1512 瑞利    5.29    5.20    5.29    57    5.20    5.19    5.29    5.19
4      1521 大億   64.70   64.70   65.00    46   64.90   64.90   65.00   64.70
5     1522 堤維西   29.80   29.80   29.85  1504   29.35   29.30   29.90   29.30
6      1524 耿鼎    9.97    9.97   10.00    35    9.98   10.00   10.00    9.97
7      1525 江申   56.00   55.90   56.00    18   56.20   56.00   56.50   55.60
8     1533 車王電   36.80   36.80   36.95    54   36.75   36.80   37.20   36.75
9      1536 和大  113.00  113.00  113.50   401  112.50  113.50  114.00  112.50
10     1568 倉佑   19.25   19.20   19.25   236   19.60   19.70   19.70   19.10
11     1587 吉茂   16.60   16.50   16.60    25   16.60   16.55   16.60   16.55
12  1592 英瑞-KY   19.80   19.70   19.80   981   20.15   20.15   20.15   19.60
13  2115 六暉-KY   39.05   39.00   39.05    26   38.95   39.40   39.40   39.05
14     2201 裕隆   19.15   19.15   19.20  2640   19.20   19.20   19.30   19.05
15     2204 中華   41.00   40.95   41.05   250   40.85   41.05   41.05   40.75
16   2206 三陽工業   22.15   22.10   22.15   764   22.05   22.05   22.15   22.05
17    2207 和泰車  575.00  574.00  575.00   326  566.00  567.00  575.00  563.00
18    2227 裕日車  265.00  264.50  265.00    80  261.50  265.00  265.50  263.00
19     2228 劍麟  122.50  122.50  123.00   416  121.00  122.50  124.00  121.50
20     2231 為升  234.50  234.50  235.50   852  241.50  241.50  243.00  231.50
21     2233 宇隆   70.20   70.20   70.40   118   70.30   70.30   70.40   70.10
22  2236 百達-KY   21.40   21.10   21.45    15   21.60   21.40   21.40   21.20
23  2239 英利-KY   91.10   91.10   91.30   106   92.40   92.10   92.10   91.00
24  2243 宏旭-KY   13.40   13.35   13.40     8   13.35   13.70   13.70   13.35
25    2497 怡利電   23.25   23.25   23.40   462   23.80   23.85   23.85   23.05
26     3346 麗清   31.10   31.05   31.10   225   31.15   31.00   31.10   30.85
27    4551 智伸科  172.50  172.50  173.50   428  171.00  171.50  175.00  171.50
28  4557 永新-KY   68.70   68.60   68.80    16   68.50   68.50   68.70   68.50
29     6288 聯嘉   25.05   25.05   25.10  4993   24.10   24.30   25.60   24.25
30     6605 帝寶   61.50   61.50   61.70    92   61.50   61.50   61.70   61.50

In [10]:
df.describe()

,成交,買進,賣出,張數,昨收,開盤,最高,最低
count,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000
mean,78.180968,78.087742,78.333548,533.741935,77.886452,78.160968,78.838387,77.379355
std,111.274435,111.115710,111.349762,992.654823,110.032740,110.401829,111.748628,109.255391
min,5.290000,5.200000,5.290000,8.000000,5.200000,5.190000,5.290000,5.190000
25%,21.775000,21.600000,21.800000,50.000000,21.825000,21.725000,21.775000,21.625000
50%,41.000000,40.950000,41.050000,225.000000,40.850000,41.050000,41.050000,40.750000
75%,69.450000,69.400000,69.600000,462.000000,69.400000,69.400000,69.550000,69.300000
max,575.000000,574.000000,575.000000,4993.000000,566.000000,567.000000,575.000000,563.000000

In [11]:
df.corr()

,成交,買進,賣出,張數,昨收,開盤,最高,最低
成交,1.000000,0.999999,0.999997,-0.098734,0.999860,0.999871,0.999913,0.999973
買進,0.999999,1.000000,0.999999,-0.098602,0.999870,0.999881,0.999922,0.999977
賣出,0.999997,0.999999,1.000000,-0.098721,0.999881,0.999892,0.999934,0.999980
張數,-0.098734,-0.098602,-0.098721,1.000000,-0.099500,-0.099617,-0.097332,-0.100773
昨收,0.999860,0.999870,0.999881,-0.099500,1.000000,0.999985,0.999978,0.999875
開盤,0.999871,0.999881,0.999892,-0.099617,0.999985,1.000000,0.999978,0.999907
最高,0.999913,0.999922,0.999934,-0.097332,0.999978,0.999978,1.000000,0.999919
最低,0.999973,0.999977,0.999980,-0.100773,0.999875,0.999907,0.999919,1.000000

In [12]:
df=df.sort_values(by=["開盤"],ascending=False)

In [13]:
df

          股票代號      成交      買進      賣出    張數      昨收      開盤      最高      最低
17    2207 和泰車  575.00  574.00  575.00   326  566.00  567.00  575.00  563.00
18    2227 裕日車  265.00  264.50  265.00    80  261.50  265.00  265.50  263.00
20     2231 為升  234.50  234.50  235.50   852  241.50  241.50  243.00  231.50
27    4551 智伸科  172.50  172.50  173.50   428  171.00  171.50  175.00  171.50
19     2228 劍麟  122.50  122.50  123.00   416  121.00  122.50  124.00  121.50
9      1536 和大  113.00  113.00  113.50   401  112.50  113.50  114.00  112.50
23  2239 英利-KY   91.10   91.10   91.30   106   92.40   92.10   92.10   91.00
21     2233 宇隆   70.20   70.20   70.40   118   70.30   70.30   70.40   70.10
28  4557 永新-KY   68.70   68.60   68.80    16   68.50   68.50   68.70   68.50
4      1521 大億   64.70   64.70   65.00    46   64.90   64.90   65.00   64.70
1   1338 廣華-KY   62.80   62.60   62.90    85   62.50   62.50   62.90   62.40
30     6605 帝寶   61.50   61.50   61.70    92   61.50   61.50   61.70   61.50
7      1525 江申   56.00   55.90   56.00    18   56.20   56.00   56.50   55.60
0      1319 東陽   46.90   46.85   46.90   825   47.05   47.05   47.40   46.50
2      1339 昭輝   46.15   46.10   46.20   462   44.95   45.50   46.40   45.40
15     2204 中華   41.00   40.95   41.05   250   40.85   41.05   41.05   40.75
13  2115 六暉-KY   39.05   39.00   39.05    26   38.95   39.40   39.40   39.05
8     1533 車王電   36.80   36.80   36.95    54   36.75   36.80   37.20   36.75
26     3346 麗清   31.10   31.05   31.10   225   31.15   31.00   31.10   30.85
5     1522 堤維西   29.80   29.80   29.85  1504   29.35   29.30   29.90   29.30
29     6288 聯嘉   25.05   25.05   25.10  4993   24.10   24.30   25.60   24.25
25    2497 怡利電   23.25   23.25   23.40   462   23.80   23.85   23.85   23.05
16   2206 三陽工業   22.15   22.10   22.15   764   22.05   22.05   22.15   22.05
22  2236 百達-KY   21.40   21.10   21.45    15   21.60   21.40   21.40   21.20
12  1592 英瑞-KY   19.80   19.70   19.80   981   20.15   20.15   20.15   19.60
10     1568 倉佑   19.25   19.20   19.25   236   19.60   19.70   19.70   19.10
14     2201 裕隆   19.15   19.15   19.20  2640   19.20   19.20   19.30   19.05
11     1587 吉茂   16.60   16.50   16.60    25   16.60   16.55   16.60   16.55
24  2243 宏旭-KY   13.40   13.35   13.40     8   13.35   13.70   13.70   13.35
6      1524 耿鼎    9.97    9.97   10.00    35    9.98   10.00   10.00    9.97
3      1512 瑞利    5.29    5.20    5.29    57    5.20    5.19    5.29    5.19

In [14]:
df.head()

        股票代號     成交     買進     賣出   張數     昨收     開盤     最高     最低
17  2207 和泰車  575.0  574.0  575.0  326  566.0  567.0  575.0  563.0
18  2227 裕日車  265.0  264.5  265.0   80  261.5  265.0  265.5  263.0
20   2231 為升  234.5  234.5  235.5  852  241.5  241.5  243.0  231.5
27  4551 智伸科  172.5  172.5  173.5  428  171.0  171.5  175.0  171.5
19   2228 劍麟  122.5  122.5  123.0  416  121.0  122.5  124.0  121.5

In [15]:
df[:5]

        股票代號     成交     買進     賣出   張數     昨收     開盤     最高     最低
17  2207 和泰車  575.0  574.0  575.0  326  566.0  567.0  575.0  563.0
18  2227 裕日車  265.0  264.5  265.0   80  261.5  265.0  265.5  263.0
20   2231 為升  234.5  234.5  235.5  852  241.5  241.5  243.0  231.5
27  4551 智伸科  172.5  172.5  173.5  428  171.0  171.5  175.0  171.5
19   2228 劍麟  122.5  122.5  123.0  416  121.0  122.5  124.0  121.5